import datetime

print(">>> Till Counter V1.0 (AUS Edition)")
print(">>> Enter Quantities for each denomination")
opID   = input("Please Enter An Operator ID: ")
TillNo = input(" Please Enter A Till Number: ")
print()
print ("Notes:")
cnt100 = input(" $100: ")
cnt50  = input("  $50: ")
cnt20  = input("  $20: ")
cnt10  = input("  $10: ")
cnt5   = input("   $5: ")
print()
print("Coins")
cnt2   = input("$2.00: ")
cnt1   = input("$1.00: ")
cnt050 = input("$0.50: ")
cnt020 = input("$0.20: ")
cnt010 = input("$0.10: ")
cnt005 = input("$0.05: ")

Tot100 = round(float(cnt100)*100, 2)
Tot50  = round(float(cnt50)*50, 2)
Tot20  = round(float(cnt20)*20, 2)
Tot10  = round(float(cnt10)*20, 2)
Tot5   = round(float(cnt5)*5, 2)
Tot2   = round(float(cnt2)*2, 2)
Tot1   = round(float(cnt1)*1, 2)
Tot050 = round(float(cnt050)*0.50, 2)
Tot020 = round(float(cnt020)*0.20, 2)
Tot010 = round(float(cnt010)*0.10, 2)
Tot005 = round(float(cnt005)*0.05, 2)

tillTot = round(Tot100+Tot50+Tot20+Tot10+Tot5+Tot2+Tot1+Tot050+Tot020+Tot010+Tot005, 2)

now = datetime.datetime.now()

print()
print("********************************")
print("   Till Counter (AUS Edition)   ")
print("********************************")
print("Till:", TillNo, "    Operator:", opID)
print(now.strftime("%d-%m-%Y %H:%M:%S"))
print("--------------------------------")
print()
print("Totals: ")
print()
print("Denom.   QTY   Line Total   ")
print(" $100:  ", cnt100, "   $", str(Tot100))
print("  $50:  ", cnt50,  "   $", str(Tot50))
print("  $20:  ", cnt20,  "   $", str(Tot20))
print("  $10:  ", cnt10,  "   $", str(Tot10))
print("   $5:  ", cnt5,   "   $", str(Tot5))
print("   $2:  ", cnt2,   "   $", str(Tot2))
print("   $1:  ", cnt1,   "   $", str(Tot1))
print("$0.50:  ", cnt050, "   $", str(Tot050))
print("$0.20:  ", cnt020, "   $", str(Tot020))
print("$0.10:  ", cnt010, "   $", str(Tot010))
print("$0.05:  ", cnt005, "   $", str(Tot050))
print()
print("--------------------------------")
print()
print("Till Total:", "$", str(tillTot))
print()
print("--------------------------------")
print("  This receipt was made using   ")
print("          Till Counter          ")
print("--------------------------------")
print("")
print("")
print("X")
print("--------------------------------")
print("       Operator Signature       ")

print()
print()

print("Copy this receipt and paste it into a text editor.")
print("Select the font Monaco or any other monospaced font.")
print("Some formatting adjustments may need to be made.")
